In [8]:
!pip install numpy

In [ ]:
import numpy as np
#creating array using numpy

#creating 1d array

arr1 = np.array([1,3,4,5,6])
print (arr1)
print(type(arr1))
print(arr1.shape)

  

[1 3 4 5 6]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([[1,3,4,5,6],[6,78,89,76,89]])  
#arr2.reshape( 1,5)
print(arr2.shape)
print(arr2)
 

(2, 5)
[[ 1  3  4  5  6]
 [ 6 78 89 76 89]]


In [15]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
##indentity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#attribute of numpy

arr =np.array([[1,2,3],[4,5,6]])

print("array:\n",arr)
print("shape:",arr.shape)
print("Number of dimension:",arr.ndim)
print("size (number of element):",arr.size)
print("data type:",arr.dtype)
print("item size(in bytes):",arr.itemsize)

array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
Number of dimension: 2
size (number of element): 6
data type: int64
item size(in bytes): 8


In [19]:
#numpy vectorise operation

arr1 = np.array([1,2,3,4,5])
arr3 = np.array([10,20,30,40,50])

#element wise operation
print("addition", arr1+arr3)
print("subtraction", arr1-arr3)

addition [11 22 33 44 55]
subtraction [ -9 -18 -27 -36 -45]


In [22]:
#unversial function

arr = np.array([1,2,3,4,5])
#square root
print(np.sqrt(arr))

#expomtenial
print(np.exp(arr))

#sine
print(np.sin(arr))

#natural  log

print(np.log(arr))


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [23]:
#array slicing and indexing

arr =np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array :\n", arr)

Array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [36]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [32]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [40]:
print(arr[1:,1:3 ]) 

[[ 6  7]
 [10 11]]


In [42]:
#modify  arr element
arr[0,0] =100
print(arr)
print(arr[0,0])

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
100


In [43]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [44]:
##statiscal concpet  ---- normalisation
## to have a mean of 0 and standard deviation of 1
 
data = np.array([1,2,3,4,5])

#calculate the mean and standard devaation

mean =np.mean(data)
std_dev =np.std(data)

#normaliz the data

normalize_data = (data-mean)/std_dev
print("Normalize data:" , normalize_data)

Normalize data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [46]:
 #mean
mean = np.mean(data)
print("mean",mean)

#Median
median = np.median(data)
print("median" , median)

#standard deviation
std_dev = np.std(data)
print(std_dev)

#variance
varienace = np.var(data)
print(varienace)

mean 3.0
median 3.0
1.4142135623730951
2.0


In [49]:
#logical opreation

data =np.array([1,2,3,4,5,6,7,8,9])

data[(data>5) &(data<9)]



array([6, 7, 8])