In [1]:
import numpy as np
import pandas as pd


In [ ]:
arr = np.random.randint(1,21 ,size=(5,5))
#print(arr)
#replacing elemnt in 3rd colum  with one

arr[:,2]=1
print(arr)



[[18  6  1  1  5]
 [18 20  1 20 14]
 [20 20  1  2  1]
 [14 11  1  7 18]
 [ 2 17  1 18  6]]


In [16]:
aa = np.arange(1,17).reshape((4,4))
print(aa)


##replacing daigonal elemn

np.fill_diagonal(aa,0)

print(aa)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]
