In [10]:
import numpy as np
import pandas as pd


In [ ]:
arr = np.random.randint(1,21 ,size=(5,5))
#print(arr)
#replacing elemnt in 3rd colum  with one

arr[:,2]=1
print(arr)



[[18  6  1  1  5]
 [18 20  1 20 14]
 [20 20  1  2  1]
 [14 11  1  7 18]
 [ 2 17  1 18  6]]


In [16]:
aa = np.arange(1,17).reshape((4,4))
print(aa)


##replacing daigonal elemn

np.fill_diagonal(aa,0)

print(aa)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [ ]:
array = np.arange(1,26).reshape((5,5))
print(array)

#array[3:,2:5]



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [22]:
array_num = np.random.randint(1,10, size=(3,4))
arr_num = np.random.randint(1,10,size =(3,4))

print(array_num+arr_num)
print(array_num-arr_num)
print(array_num/arr_num)
print(array_num*arr_num)





[[ 6  3  9  5]
 [11  6 12  2]
 [11  7  8 10]]
[[-2  1 -5 -3]
 [ 5  4  2  0]
 [-7  5 -6  4]]
[[0.5        2.         0.28571429 0.25      ]
 [2.66666667 5.         1.4        1.        ]
 [0.22222222 6.         0.14285714 2.33333333]]
[[ 8  2 14  4]
 [24  5 35  1]
 [18  6  7 21]]


In [26]:
array1 =np.arange(1,17).reshape(4,4)
print(array1)

row_sum = np.sum(array1 , axis=1)
col_sum = np.sum(array1,axis=0)

print(row_sum)
print(col_sum)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[10 26 42 58]
[28 32 36 40]


In [27]:
array1_num = np.random.randint(1,10, size=(5,5))

mean  = np.mean(array1_num)
print(mean)

medain = np.median(array1_num)
print(medain)

std_dev = np.std(array1_num)
print(std_dev)

vari = np.var(array1_num)
print(vari)

4.68
5.0
2.3785709995709605
5.657599999999999


In [38]:
array =np.random.randint(1,11,size =(4,4))
print(array)
row_array = np.random.randint(1, 11, size=(4,))
print(row_array)

result = array-row_array[:,np.newaxis]
print(result)

[[ 9  5  2 10]
 [ 2  1  9  5]
 [ 3  3  9  3]
 [ 2  3  8  7]]
[9 3 4 2]
[[ 0 -4 -7  1]
 [-1 -2  6  2]
 [-1 -1  5 -1]
 [ 0  1  6  5]]


In [39]:
matrix = np.random.randint(1,11,size=(3,3))
print('orignial matrix \n', matrix)

det = np.linalg.det(matrix)
print(det)

inv = np.linalg.inv(matrix)
print(inv)

egin = np.linalg.eigvals(matrix)
print(egin)



orignial matrix 
 [[5 9 2]
 [2 1 1]
 [1 2 8]]
-98.99999999999999
[[-0.06060606  0.68686869 -0.07070707]
 [ 0.15151515 -0.38383838  0.01010101]
 [-0.03030303  0.01010101  0.13131313]]
[-1.71059761  5.89795148  9.81264613]


In [40]:
array1 = np.random.randint(1, 11, size=(2, 3))
array2 = np.random.randint(1, 11, size=(3, 2))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform matrix multiplication
result = np.dot(array1, array2)
print("Matrix multiplication result:")
print(result)

Array 1:
[[ 3  7 10]
 [ 8  2 10]]
Array 2:
[[ 2 10]
 [10  6]
 [ 9 10]]
Matrix multiplication result:
[[166 172]
 [126 192]]


In [12]:
arr1 = np.random.randint(1,9, size =(3,3))
print(arr1.shape)

reshape_array = arr1.reshape((1,9))
print('Reshaped_arr',reshape_array)

reshape_array1 = arr1.reshape((9,1))
print('Reshaped_arr',reshape_array1)


(3, 3)
Reshaped_arr [[7 7 8 7 5 1 3 6 1]]
Reshaped_arr [[7]
 [7]
 [8]
 [7]
 [5]
 [1]
 [3]
 [6]
 [1]]


In [14]:
array = np.random.randint(1,21,size =(5,5))
print("oringal array")
print(array)

#faltten
flat = array.flatten()

print("flat array")
print(flat)

resdaape =  flat.reshape(5,5)

print(resdaape)

oringal array
[[ 5  7 15  1 17]
 [14 11 10  1 14]
 [ 5 16  8  8 20]
 [15 19 16  9 13]
 [15 14 19  3 14]]
flat array
[ 5  7 15  1 17 14 11 10  1 14  5 16  8  8 20 15 19 16  9 13 15 14 19  3
 14]
[[ 5  7 15  1 17]
 [14 11 10  1 14]
 [ 5 16  8  8 20]
 [15 19 16  9 13]
 [15 14 19  3 14]]


In [17]:
array = np.random.randint(1,21,size =(5,5))
print(array)
corner = array[[0,0,-1,-1],[0,-1,0,-1]]

print(corner)


[[ 1 10  7 10  9]
 [11 14 14 13  6]
 [12 15 17  1 12]
 [17 12  6 10  1]
 [11 16 16  7 15]]
[ 1  9 11 15]
